- text/1000-migrations.rst
1. Object name `schema::Migration` (instead of `sys::..`)
2. Add `initial` revision name
3. Fix typo in syntax
> rfc1000: Tiny clarifications

- README.md
- text/0002-doing-an-edgedb-release.rst
- text/0002-edgedb-release-process.rst
This can be merged but I will have to expand on the last sections
> Add a description of producing a release

- README.md
- text/1004-transactions-api.rst
* In particular "Failover and Replication Pre-RFC"
* And "Stateful Connection Configuration Pre-RFC"
> Merged discussions to RFC1004

- README.md
- text/1003-cli-naming.rst
- text/1004-transactions-api.rst
Old body kept for posterity. The amount of change is big enough it's easier to read this only looking at the new content though.
> Second attempt at the Consistent CLI Design RFC

- text/1004-transactions-api.rst
We ultimately decided to rename the two to
"raw_transaction()" and "retrying_transaction()".
> Rename try_transaction() & retry() methods

- text/1001-edgedb-server-control.rst
- text/1006-simplified-cli.rst
See https://github.com/edgedb/edgedb/issues/2647 for motivation
> Split `edgedb server` into `edgedb server` and `edgedb instance`

- text/1008-tls-and-alpn.rst
> Align RFC 1008 with recent decisions on TLS

- README.md
- text/1009-group.rst
GROUP is the name of the statement, really. I made most of
the text consistent with that but forgot about the title.
> Rename the RFC from GROUP BY to just GROUP

- text/1006-simplified-cli.rst
[Rendered](https://github.com/fantix/rfcs/blob/instance-list/text/1006-simplified-cli.rst)
> Update RFC 1006: include `instance list`

- text/1009-group.rst
Updating grouping to be a set of keys, update all examples to be
actual output from the real draft implementation, fix some other
errors.
> RFC 1009: Update examples, grouping definition

- README.md
- text/1009-group.rst
It's implemented and merged. We can argue about any details some more
if anybody wants, but otherwise I think it is decided mostly.
> Mark GROUP as final

- README.md
- text/1012-range-types.rst
Initial proposal to add range types to EdgeQL.
> RFC 1012: Range types

- text/1015-full-text-search.rst
A draft proposal of the full-text search funcitonality for EdgeDB.
> RFC 1015: Full text search

- text/1022-freetypes.rst
This RFC proposes new type language syntax for declaring ad-hoc free object types as well as some modifications to our current SDL.
> 1022: Typing free objects & simplifying SDL syntax. Initial draft

- text/1015-full-text-search.rst
Bring the RFC document and implementation into sync. We've changed some names of various `fts` parts and added new enums.
> Update the RFC 1015

- text/1025-branches.rst
Add more details to what we expect from the CLI and how we expect developers to work with the branches.
> 1025: Update the branches RFC.

- README.md
- text/1027-no-factoring.rst
- text/1030-no-factoring.rst
Draft an RFC proposing the elimination of path factoring.
Any feedback about what to expand?
> Simplifying path resolution

- text/1027-no-factoring.rst
Change is implemented in https://github.com/edgedb/edgedb/pull/7805
> [resolution] Officially propose the FOR loop enhancement

- README.md
- text/1015-full-text-search.rst
- text/1023-splats.rst
- text/1025-branches.rst
- text/1026-net-module.rst
I've left some in Draft that are at least partially implemented,
since I'm not totally sure if the RFC reflects the current state.
> Mark a bunch of RFCs accepted, update index

- text/1028-cli-hooks.rst
A proposal to add migration and fixture hooks to gel projects.
> RFC 1028: CLI hooks

- text/1028-cli-hooks.rst
- **branch merge/rebase does not switch**
- **[project-hooks] -> [hooks]**
- **minor reword**
- **array of strings, /bin/sh, status codes**
> Followup for CLI hooks

- text/1029-rbac.rst
And allow multiple permissions
> 1029: Rename Function.require_permission to required_permissions

- text/1029-rbac.rst
Instance config is pretty substantial.
> 1029: Make branch config have a perm, require superuser for instance config

- text/1029-rbac.rst
> Tweak RBAC RFC formatting
